language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/spring-boot/.m2/repository'
    - '$HOME/spring-boot/.gradle'

script:
  - 'cd ./spring-boot'
  - './gradlew clean build'

notifications:
  email:
    recipients:
      - sunfkkc@kakao.com