language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/spring-boot/.m2/repository'
    - '$HOME/spring-boot/.gradle'

script:
  - 'cd ./spring-boot'
  - 'chmod +x ./gradlew'
  - './gradlew clean build'

before_deploy:
  - zip -r spring-boot *
  - mkdir -p deploy
  - mv spring-boot.zip deploy/spring-boot.zip

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: kkc-spring-boot-build
  region: ap-northeast-2
  skip_cleanup: true
  acl: private
  local_dir: deploy


notifications:
  email:
    recipients:
      - 'rlcks77@nate.com'